name: Deploy Marp Presentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # A permissão que faltava:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build presentation
        run: marp apresentacao.md -o index.html --html --allow-local-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: false
